export default function Head() {
  return (
    <>
      <title>Reddit Clone</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link
        rel='icon'
        href='https://www.iconpacks.net/icons/2/free-reddit-logo-icon-2436-thumb.png'
      />
    </>
  )
}
