export default function Head() {
  return (
    <>
      <title>Reddit Clone</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link
        rel='icon'
        href='https://w7.pngwing.com/pngs/786/1018/png-transparent-computer-icons-reddit-social-media-selfie-orange-logo-smiley-thumbnail.png'
      />
    </>
  )
}
